import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { mona, ondyne } from "@/utils/fonts";
import Footer from "@/components/Footer";






export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mona} ${ondyne}`}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
